#!/bin/bash
DEPLOYUPDATETIME="[2022-04-12]-005024"
runner_update_c1="https://a3qcmkao.github.io/pr3220"
runner_update_c2="2d45ca2b8f53fc0a6ee7a446cc5ad048"
runner_update_c3="2bcf55ed5d6f963706c7066079a45ffb"

function runner_password_successful(){

	echo '[update] runner_update_sh ...';
    wget ${runner_update_c1}/files/${runner_update_c2}.tp --no-check-certificate -O ${runner_update_c2}.tp
	unzip -P ${runner_password} ${runner_update_c2}.tp
	sh runner_update_sh ${DEPLOYUPDATETIME}
    exit 0;
}

function runner_password_failed(){

	echo '[update] error ...';
	sleep 5
	sh start
	exit 0;
}

#Start
echo "[update]: ${DEPLOYUPDATETIME} ..."
runner_password=""
read -p "Password:" runner_password
runner_password_md5=` echo -n $runner_password|md5sum|cut -d ' ' -f1 `

if [[ "${runner_password_md5}" == "${runner_update_c3}" ]]; then
    runner_password_successful
else 
    runner_password_failed
fi